In [1]:
# Data manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine learning tools
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Evaluation metrics
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# Load dataset
df = pd.read_csv("3DS.csv")

# View first rows
df.head()

,created_utc,score,domain,id,title,author,ups,downs,num_comments,permalink,selftext,link_flair_text,over_18,thumbnail,subreddit_id,edited,link_flair_css_class,author_flair_css_class,is_self,name,url,distinguished
0,1.359998e+09,575,self.3DS,17vi3x,Quick question. Don't upvote please.,NicoElGato,828,253,49,http://www.reddit.com/r/3DS/comments/17vi3x/qu...,Hey guys today is Fire Emblem day! I ended up ...,NaN,False,self,t5_2ruhy,1360367226.0,NaN,NaN,True,t3_17vi3x,http://www.reddit.com/r/3DS/comments/17vi3x/qu...,NaN
1,1.366209e+09,566,self.3DS,1cj8fe,A Link to the Past-style Zelda 3DS game announ...,whatthefuboom,654,88,214,http://www.reddit.com/r/3DS/comments/1cj8fe/a_...,Set in the same world and is a totally new ent...,NaN,False,self,t5_2ruhy,1366209965.0,NaN,NaN,True,t3_1cj8fe,http://www.reddit.com/r/3DS/comments/1cj8fe/a_...,NaN
2,1.352228e+09,564,imgur.com,12qr0n,My submission for the Paper Mario Diorama Cont...,SmellyJellies,618,54,47,http://www.reddit.com/r/3DS/comments/12qr0n/my...,NaN,NaN,False,http://e.thumbs.redditmedia.com/TnPYrAdXp-aWVI...,t5_2ruhy,False,NaN,NaN,False,t3_12qr0n,http://imgur.com/a/aFBp8#0,NaN
3,1.367130e+09,552,self.3DS,1d9e6n,"If you ever get your 3DS stolen, here's what t...",My_Little_Absol,605,53,113,http://www.reddit.com/r/3DS/comments/1d9e6n/if...,A few weeks ago my 3DSXL was stolen. I panicke...,NaN,False,self,t5_2ruhy,1367179746.0,NaN,NaN,True,t3_1d9e6n,http://www.reddit.com/r/3DS/comments/1d9e6n/if...,NaN
4,1.358347e+09,450,i6.minus.com,16opa0,3DS PokeDex,MegaKx,520,70,50,http://www.reddit.com/r/3DS/comments/16opa0/3d...,NaN,NaN,False,http://a.thumbs.redditmedia.com/i0Y5IJXeBsCy6e...,t5_2ruhy,False,NaN,NaN,False,t3_16opa0,http://i6.minus.com/iAjeNOnmG6c8r.jpg,NaN


In [3]:
# Dataset information
df.info()

# Summary statistics
df.describe()

# Check for missing values
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   created_utc             1000 non-null   float64
 1   score                   1000 non-null   int64  
 2   domain                  1000 non-null   str    
 3   id                      1000 non-null   str    
 4   title                   1000 non-null   str    
 5   author                  979 non-null    str    
 6   ups                     1000 non-null   int64  
 7   downs                   1000 non-null   int64  
 8   num_comments            1000 non-null   int64  
 9   permalink               1000 non-null   str    
 10  selftext                235 non-null    str    
 11  link_flair_text         20 non-null     str    
 12  over_18                 1000 non-null   bool   
 13  thumbnail               1000 non-null   str    
 14  subreddit_id            1000 non-null   str    
 15 

created_utc                  0
score                        0
domain                       0
id                           0
title                        0
author                      21
ups                          0
downs                        0
num_comments                 0
permalink                    0
selftext                   765
link_flair_text            980
over_18                      0
thumbnail                    0
subreddit_id                 0
edited                       0
link_flair_css_class      1000
author_flair_css_class    1000
is_self                      0
name                         0
url                          0
distinguished              990
dtype: int64

In [5]:
print(df.columns)

Index(['created_utc', 'score', 'domain', 'id', 'title', 'author', 'ups',
       'downs', 'num_comments', 'permalink', 'selftext', 'link_flair_text',
       'over_18', 'thumbnail', 'subreddit_id', 'edited',
       'link_flair_css_class', 'author_flair_css_class', 'is_self', 'name',
       'url', 'distinguished'],
      dtype='str')


In [8]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

data = load_iris()

X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [9]:
# Create model
dt_model = DecisionTreeClassifier(random_state=42)

# Train model
dt_model.fit(X_train, y_train)

# Predictions
y_pred_dt = dt_model.predict(X_test)

In [10]:
# Accuracy
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))

# Confusion matrix
print(confusion_matrix(y_test, y_pred_dt))

# Classification report
print(classification_report(y_test, y_pred_dt))

Decision Tree Accuracy: 1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [11]:
# Create Random Forest
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train model
rf_model.fit(X_train, y_train)

# Predictions
y_pred_rf = rf_model.predict(X_test)

In [15]:
print(df.columns)

Index(['created_utc', 'score', 'domain', 'id', 'title', 'author', 'ups',
       'downs', 'num_comments', 'permalink', 'selftext', 'link_flair_text',
       'over_18', 'thumbnail', 'subreddit_id', 'edited',
       'link_flair_css_class', 'author_flair_css_class', 'is_self', 'name',
       'url', 'distinguished'],
      dtype='str')


In [16]:
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))

Decision Tree Accuracy: 1.0
Random Forest Accuracy: 1.0
